@echo off 
color 0B 
title Backend Server 
echo [BACKEND] Creating virtual environment... 
python -m venv venv 
echo [BACKEND] Activating virtual environment... 
call venv\Scripts\activate 
echo [BACKEND] Upgrading pip... 
python -m pip install --upgrade pip 
echo [BACKEND] Installing requirements... 
pip install -r requirements.txt 
echo [BACKEND] Changing to backend directory... 
cd backend 
echo [BACKEND] Running migrations... 
python manage.py migrate 
echo [BACKEND] Populating muscle groups... 
python manage.py populate_muscle_groups 
echo [BACKEND] Populating workouts... 
python manage.py populate_workouts 
echo [BACKEND] Pulling from Supabase... 
python manage.py pull_from_supabase --full 
echo [BACKEND] Syncing to Supabase... 
python manage.py sync_to_supabase --full 
echo. 
echo [BACKEND] Starting Django server... 
python manage.py runserver 0.0.0.0:8000 
echo. 
echo Server stopped or failed to start. 
pause 
del "%~f0" & exit 
